language: sh
script: make test
notifications:
  slack:
    rooms:
      secure: U11wBLcqMZtV9NM1UuZLGm/Mk6WCMYDX75jjd44l5rGI32tggYed6yUowIa+9UDxh0i8pU2AhNBk61eF+juf10c+e214SZvH+S70s8p1/kpwKaqBohwMSAeY+eIgxIVn31p/njWFo1+sUdVs5R1R1P9UFe8k3TpTf3mCd+nG5OKl5d1J39TUsrPRubxbZka2JwiIuzq9xFzVIw/1guHxE1KSqesyiEHE62/PTRqp/Vxr7s9scYzbtrx21dtJ3fo+TCcb6OERdfats6rTiVdy7k55WHu7gC4LurLE6QcyRpJcwWDCwNzWrHEZu2ewH1y6s/cCS2GzjuEZuiaMY3WCb24JSIr/AjnkkJ3bTsAbWE522OG6QvqG/dbWxMylmHdz+s2SDeObNFRA1XChvzRng8Za6Z8UzFUU1IxFESwZDpya3CqXdv+HM3ugAiHaGu1BfY6VozsVJksdzJwiiPcrYyScd10LXROG564+pXAbO5fzkVIIs3vzw9BqHIAAq+Qep09Rt4MfO7CwYe+k4H2ZKMj+d/GHlS56svCsLpVqzlggkB/NweAe6XHs/wrTusfH268o6ym/mhZUJO+yMbN+u5/BcGCDtfriwBVc3iL/91Ue5Lns46cPDb9rUZeXQY+F/86tJApOZ6pP4eN1/7cYe42uGZxOIG6uLtJbjT5Svc8=
