language: sh
script: make test
notifications:
  slack:
    rooms:
      secure: Mcle/4OvAtTG8iZ7fPErpLeT2sjqEOoPB1RPzDyhaW+0xqq8wg5HGHI4VQYLqF+JPpFIoWCciwpLYTmwQKV61zjvQ+JoNTBFeX/8+HgTlxELxNgOA+4Lbl0hVBQqAtWKLtBl7AvC3wZoAHerNu/ikuRL5sqk45cBKuW1S77zFB6lQLyjv4c19Fer9WT3zjMLGI8z0hL2QSJq9A2BdGKIN386fU6sVyl+g9xZXoCxWAPpTr9aUMcaDJ1R7LsuYTBuvkj9QuzAjpBThyA+TXwhn19lsacXEZ3G144By5zSCJjdM1qkqNhcg0BCnEN9OVDPlDBXNpIur88X6YoyfXOCPwEN1jdykbxcuqQLO111XqrfPj914FYhD03XAlqRLHny+3unI3PwY39kLhd0z29TtE9vhJZDilreFZBrauupcjXG1HNoY+7T14r9FjG/zBrlp7XOscvywAsyy9iWK62zay+nnF3ih3tdORqMORJkH4qPfKSQ8Fcx39PjXkUrBF3Stl2xmZjVIv2pXpcYu4Zj8zzqnQwyDjiHrSVgs7UWyUPtGBme+aAXeitBDXPR+LHsovL8eeMTl65HDpXfbxFqBSEQvXplOxmIEX8AT1LSgTivIWqw/FWQdCsivCP9WZFT/ERgRv0iSSK+C+b3YQNTZWrEqIQzK5VGp9T4XkM49zk=
